:toc: macro
:toc-title:
:sectanchors:
:toclevels: 99

# Hello GraphQL

toc::[]

2017 November 8

## Hello World

GraphQL is a technology that enables clients to fetch just the data they need from backends in a predictable and safe way. Predictable because the query shape is the data shape, safe because queries operate on strongly typed data. At its core GraphQL is just a http://facebook.github.io/graphql[specification]. The surrounding community extends it, builds tools around it, and helps evolve it. It was originally developed at Facebook in 2012 but later open-sourced in 2015. Over the following two years many companies adopted it for internal APIs (https://open.nytimes.com/react-relay-and-graphql-under-the-hood-of-the-times-website-redesign-22fb62ea9764[New York Times], https://www.youtube.com/watch?v=T3FbZsYXi50[IBM], https://dev-blog.apollodata.com/courseras-journey-to-graphql-a5ad3b77f39a[Coursera], ...), but some companies also launched public APIs (https://www.youtube.com/watch?v=Baw05hrOUNM[Twitter], https://developer.github.com/v4/[Github], https://www.yelp.com/developers/graphql/guides/intro[Yelp], ...).

Here is an example of a GraphQL query:

```graphql
query Product(id: "ab781du3", language: EN) {
  name,
  description,
  sizes: {
    name,
    stock,
  }
}
```

## A mental model

### Queries

. client makes a request
. request gets syntactically validated
. request gets validated against schema
. requested fields get resolved into data
. response is sent back

### Mutations

. client makes a request
. request gets syntactically validated
. request gets validated against schema
. mutation is carried out
. requested response fields are resolved into data
. response is sent back

### Subscriptions

. client makes a request
. request gets syntactically validated
. request gets validated against schema
. new subscriber for event source is registered
. each event from source is executed against with originally given query
. ...then the resolved data is sent back

## A Specification

GraphQL is a specification that chiefly defines a type system and a query language.

### Not everything is specified

Many aspects of GraphQL that will need to be solved in production are intentionally left unspecified. Some notable omissions include what transport to use (HTTP is not mentioned anywhere for example), how authorization should work, how error handling should work. This is a tradeoff. A key advantage is that the community can explore unspecified spaces to discover new solutions that offer optimal tradeoffs. But now efforts will be fragmented leading to a host of negatives like more decisions to make in userland and less mature libraries, tooling, etc. But arguably the wrong standard is worse than no standard and so for example it seems reasonable that if authorization architecture looks very different from one company to the next it should not be standardized. And certainly one may hope that if over time if a clearly superior design pattern emerges from the community it will be folded back into the core spec somehow, or failing that perhaps instead specified as an extension like Facebook's https://facebook.github.io/relay/graphql/connections.htm[Relay Cursor Connections Specification].

## Anatomy of GraphQL Schema

This section will introduce GraphQL's type system.

References:

- https://github.com/sogko/graphql-schema-language-cheat-sheet[cheatsheet]

### Scalers

GraphQL has a base set of types that all other types are just compounds of. These base types are referred to as https://stackoverflow.com/questions/6623130/scalar-vs-primitive-data-type-are-they-the-same-thing[scalers] and are:

* Int - signed 32-bit integer
* String - UTF-8 character sequence
* Float - signed double-precision floating-point value
* Boolean - true or false
* ID - a string for uniquely identifying something in a non-human-readable way

A GraphQL implementation may also extend this set of scalers with new ones e.g. Email, Date, PhoneNumber, URL, etc.

Example:

```
type Product {
  id: ID
  name: String
  price: Float
  stock: Int
  tood: Boolean
}
```

### Enumeration

Enumeration types allow expressing that a field will be one of several different values. It is a better choice than a string when the possible values are within a controlled set. A good candidate for enumerations can be strings that you see in code being tested for concrete matches like `gender == "men"` and `size == "xs"`. An enumeration in GraphQL is like a scaler type in that it is a leaf of your query.

```
Size = {
  S
  M
  L
}
```
```
enum Gender = {
  MALE
  FEMALE
}
```
```
enum Order_Status = {
  INVOICED
  PICKED
  PACKED
  SHIPPED
  DELIVERED
  RETURNED
}
```


### Object

Object types provide the means to create a set of field names and their corresponding types that logically represent something concrete in the author's domain like a product, article, comment, or user. Unsurprisingly they tend to be the workhorse of an author's schema.

```
type Product = {
  id: ID
  name: String
  price: Float
  countryOfManufacture: Country
  brand: Brand
  colour: Colour
  gender: Gender
}
```

### List

List types allow expressing many of some value (Fun fact, this is sometimes referred to as a non-deterministic value).

```
type SearchResult = {
  products: [Product]
}
```

### Non-Null

Non-Null types allow expressing that a field will never be `null`. If you are familiar with Maybe types (sometimes called Option type) from Haskell Scala Rust Swift Elm and others then you can view this type as a kind of reversal. In most programming languages the possibility of `null` is opted in by the user, but in GraphQL every field is maybe null by default, forcing schema authors to opt-out when they don't want this type. So somewhat paradoxically `Non-Null` "types" are really a means of simplifying and stripping away type information from fields!

Consider the following schema example:

```
query {
  products: [Product]
}
```

Ignoring the type of Product, statically typing the query result would look something like this, for example:

In Flowtype:

```typescript
type QueryResultProducts = null | Array<null | Product>
```

In Haskell:

```haskell
type QueryResultProducts = Maybe [Maybe Product]
```

But if the GraphQL schema author now uses some `Non-Null` types for their schema:

```
query {
  products: [Product!]!
}
```

Look what happens to the static types of the query result:

In Flowtype:

```typescript
type QueryResultProducts = Array<Product>
```

In Haskell:

```haskell
type QueryResultProducts = [Product]
```

Hopefully you can see now how `Non-Null` types in GraphQL are really a way to remove type information, not add it.

When `null` is impossible client code is simplified becuase they have fewer edge cases to account for. But care should be taken by schema authors to not over-promise when designing their schema too. Firstly, changing a field type from not-nullable to nullable is a breaking change while the reverse is not. Secondly, null propagates up the tree of fields to the first nullable field. So if null occurs when it was guaranteed not to the data dropped on the result will likely be worse than had null been a more granular possibility. For example instead of a single item in a list having an image link field be null the entire list of items might become null instead.

Both of these points are discussed in finer detail with examples by Caleb Meredith in https://medium.com/@calebmer/when-to-use-graphql-non-null-fields-4059337f6fc8[When to use GraphQL Non-Null Fields].


### Interface

Interface types allow expressing a set of fields that other Object types must have.

```
interface Product {
  id: ID
  name: String
  price: Float
  countryOfManufacture: Country
  brand: Brand
  colour: Colour
  gender: Gender
}

type Bag implements Product {
}

type Shoe implements Product {
}

```

This has multiple benefits. For schema authors working at scale Interfaces are a design tool helping them reason about data relationships and enforcing those relationships at the server level. For clients, interfaces allow queries on unions to be simplified in some cases.

### Union

Union types allow expressing that a field may be one of several different Object types.

Example:
```
type Product {
  id: ID
  name: String
  price: Float
}

type Article {
  id: ID,
  title: String
  author: String
}

union SearchResult = Product | Article
```

You may be wondering how one queries on such a type:

```
search(term:String) {
  searchResult: {
    # ... fields for Product or Article ...???
  }
}
```

We will answer this once we dive into queries.

You may also be wondering how this relates to Sum Types (AKA Tagged Union Types, variant Record, Discriminated Union, Disjoint Union). My take is that while GraphQL Union types have some similarities to Sum Types they are less flexible given that they are constrained to being a union of just Object types. By comparison, Sum Types in the type systems of Haskell Rust Swift and many other programming languages are effectively a superset of enums:

1. Analog to GraphQL `Enumeration`:
+
```haskell
type Size = S | M | L
```
+
```haskell
type Gender = Male | Female
```

2. Analog to GraphQL `Union`:
+
```haskell
type SearchResult = Product String String Float | Article String String String
```

Alas in GraphQL we must cope with less general/flexible types, but thankfully taken together can still model our data with expressivity at least approaching Sum Types. I haven't yet taken the time to confirm with the community if this is true but I suspect that GraphQL's design decisions here were related to other design considerations on the query side, when actually fetching data against these types. As we will see queries against enum types versus union types are quite different.

If you do not have extensive experience modelling your data with Sum or Sum-like types you may find this article by Chad Austin useful: https://chadaustin.me/2015/07/sum-types/[Sum Types Are Coming: What You Should Know].





### Input Object
TODO

## More about Interfaces and Unions

* unions are good for modelling a field which may be of totally different types. For example an error or a value
* interfaces are good for modelling a field which may be one of several related values, for example maybe socks shoes coats gloves glasses and so on all share a base interface type.
* a nice feature of interfaces for clients making queries is that field type qualifications via e.g. inline fragments are not needed for interface-level fields. Only once the user wants fields particular to some type implementing the interface will they then need to break out into slightly more verbose query syntax.
* Conversely a field which is a union type can only be queried upon with inline fragments which first qualify the type.
* the effect on a query's verbosity probably shouldn't be the main concern however. Instead the domain itself should inform what the relationship of the data is and that in turn should inform how to model the data. For example I have seen one use-case for unions be putting errors inline with data such that a field can either be the data you requested or some error like authorization failure. Reference: TODO

## The tradeoffs of opt-in versus opt-out

* GraphQL is unlike typical REST but similar to direct DB queries in that its an opt-in model rather than hard-coded results
* This means that clients can expect their actual queries to grow in size in their codebase since they now need to be explicit about every piece of data they use. It is literally impossible to work with data that is not explicitly stated in the query.
* While this appears at first like a step backwards for the needs of clients it turns out that the extra typing is a small price to pay for query result predictability.
* There are other benefits too. Developers may have an easier time reading the code later since they won't have to wonder about the query results.
* Tooling now has a standard way to generate application-level types by combining queries in the app with the server's schema definition.
* Developers can also copy-paste into a tool like GraphiQL to interactively explore data, then copy-paste back into their code, forming a much tighter loop than you would get with e.g. Swagger.
* Another benefit is that backend teams know precisely which field are popular or not, thus informing decisions about where to optimize or how to evolve a schema. Advantages like these seem to greatly outweigh the con of added verbosity in a few query sites.
* another benefit for backend developers is evolving APIs becomes easier when you know anything you add will not be noticed by clients or bloat their results perhaps without them even knowing it.

## Anatomy of GraphQL Queries

Hopefully you now have a sense of what GraphQL is. Lets survey some of its main features so that you have a deeper understanding of what it can and cannot do in more precise operational terms.

### Document
### Selection Set
### Operation (query, mutation, subscription)
### Aliases
### Functions
### Opt-in
### Directives
### Fragments
### Variables

## Case Study

TODO

### Making a query

```
fragment RelatedProduct on Product {
  id,
  name,
  price: {
    amount(formatted: true)
  },
  primary_image(height: 50): {
    width,
    height,
    alt_text
  }
}
```
```
fragment AllMeasurements on ProductMeasurements {
  ... on Shirt {
    shoulders,
    chest,
    length,
    sleeve,
  }
}
```
```
query product(id: $product_id, language: $language, region: $region) {
  sku,
  name,
  summary,
  description,
  material_facts,
  in_my_wishlist,
  model: {
    description,
    size: {
      chest,
      hip,
      shoulder,
      waist,
    }
  },
  price {
    amount
    amount_formatted: amount(formatted: true),
    currency_name
  },
  styled_with: {
    ...RelatedProduct
  },
  images(width: 400): {
    width,
    height,
    alt_text
  },
  sizes: {
    id,
    name
    measurements: {
      ...AllMeasurements
    },
    stock,
  },
  category: {
    product_sizing_diagram,
    id,
    name
    products (limit: 7): {
      ...RelatedProduct
    }
  },
  brand: {
    id,
    name
    products(limit: 5, like_product: $product_id): {
      ...RelatedProduct
    }
  }
}
```

## Ecosystem

* queries are typed out literally in code, as-you-type validation
* GraphiQL, Voyager, Graphcool, Graphene, Relay, Apollo Client, Apollo Engine
* Authorization goes into the Authorization header
* user context aka `viewer` pattern
* Localization goes into Accept-Language header
* backend teams know how their servers are being used
* frontend teams only pay for what they use, example at SSENSE with price field

### Schema Driven Development

Interestingly schema definitions like the examples we saw while introducing the type system or presenting the case study can be transformed into a functioning GraphQL server by https://github.com/apollographql/graphql-tools[Apollo GraphQL Tools]. This is a declarative way of creating a GraphQL service because you simply say what the interface is and it becomes so. Apollo has termed this approach https://www.apollographql.com/docs/graphql-tools/index.html#recommendations[the GraphQL-first philosophy].

## Novelty

* Some of the things that make GraphQL notable are:

** its conservative iterative and organic development over years of production experience
** originated as a data solution for mobile apps, still driven by needs of frontend engineers
** particularly strong ecosystem support for React
** its rich type system including union types and opt-in null-free
** its opt-in field-level granularity query model
** its fields-are-functions query model
** its ecosystem of tooling
** its fundamental flexibility, such as not even requiring HTTP
** its interface unification of streaming and request-response

Some other technologies have overlapping benefits like https://grpc.io[gRPC]  (strong types, unified streaming/request-response interface) or http://netflix.github.io/falcor/[Falcor] (graph queries, data layer abstraction), but GraphQL is ultimately highly unique in its intersection of characteristics.

## An Ecosystem

TODO

## Summary

* GraphQL is a **specification** with _many implementations_
* GraphQL was originally created at Facebook but is now developed in the open by many companies and engineers.
* https://www.apollodata.com/[Apollo] is the/one of the most directly involved/invested companies in furthering the technology (not consumer but driver) outside of Facebook. Apollo is part of https://www.meteor.com[Meteor].

## References

* http://graphql.org/learn[official docs]
* http://facebook.github.io/graphql[spec]
* https://www.howtographql.com/
* https://github.com/chentsulin/awesome-graphql[awesome-graphql]
* https://twitter.com/tomdale/status/786951612053020672?lang=en
* https://stackoverflow.com/questions/34726666/real-world-example-of-graphqlinterfacetype-and-graphqluniontype
